version: "2"

services:

  load_balancer:
    image: dockercloud/haproxy:1.2.1
    links:
        - web
    ports:
       - "8080:80"
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  cache:
    image: redis

  db:
    image: mysql
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - /tmp/datadir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=7h0u54nd3y35

  web:
    build: .
    depends_on:
      - db
      - cache
    links:
      - db
      - cache
    environment:
      - DB_NAME=nbrp
      - DB_USER=root
      - DB_PASSWORD=7h0u54nd3y35
      - DB_HOST=db
      - CACHE_EXPIRATION=120s
      - RESPONSE_TIME_THRESHOLD=0.25s
      - REDIS_HOST=cache
      - APP_PORT=8080
    command: ["/wait-for-it.sh", "db:3306", "--", "/nbrp"]
